import type { Metadata } from "next";
import { ThemeToggle } from "../../modules/theme/toggle-theme";

export const metadata: Metadata = {
  title: "InnoSense AI Interview | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="auth-layout">
      <ThemeToggle />
      {children}
    </div>
  );
}
