import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "InnoSense AI Interview | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="auth-layout m-2 md:m-0">{children}</div>;
}
